package:
  name: clinicalgraphics
  version: "0.1"
  
source:
  path: ../
#  git_rev: 0.1
#  git_url: https://github.com/EelcoHoogendoorn/ClinicalGraphics.git
 

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - chaco
    - pyqt
    - kiwisolver

test:
  requires:
    - nose
